parameters:
# configured in extension load.
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Psr\Clock\ClockInterface: # Interface
        class: Symfony\Component\Clock\NativeClock

# > --- lcobucci/jwt ---
    Lcobucci\JWT\Decoder: # Interface
        class: Lcobucci\JWT\Encoding\JoseEncoder

    Lcobucci\JWT\Encoder: # Interface
        class: Lcobucci\JWT\Encoding\JoseEncoder

    Lcobucci\JWT\Signer: # Interface
        factory: [ 'Atlance\JwtCore\Token\Factory\SignerResolver', 'resolve' ]
        arguments: [ '%atlance_jwt_auth.algorithm_id%' ]

    jwt_auth.public_key:
        class: Lcobucci\JWT\Signer\Key # Interface
        factory: [ 'Lcobucci\JWT\Signer\Key\InMemory', 'file' ]
        arguments: [ '%atlance_jwt_auth.public_key%' ]

    jwt_auth.private_key:
        class: Lcobucci\JWT\Signer\Key # Interface
        factory: [ 'Lcobucci\JWT\Signer\Key\InMemory', 'file' ]
        arguments: [ '%atlance_jwt_auth.private_key%', '%atlance_jwt_auth.private_passphrase%' ]

    Lcobucci\JWT\Parser: # Interface
        class: Lcobucci\JWT\Token\Parser
        arguments: [ '@Lcobucci\JWT\Decoder' ]

    Lcobucci\JWT\ClaimsFormatter: # Interface
        class: Lcobucci\JWT\Encoding\MicrosecondBasedDateConversion

    Lcobucci\JWT\Validator: # Interface
        class: Lcobucci\JWT\Validation\Validator

    Lcobucci\JWT\Builder: # Interface
        class: Lcobucci\JWT\Token\Builder
        arguments: [ '@Lcobucci\JWT\Encoder', '@Lcobucci\JWT\ClaimsFormatter' ]

    Lcobucci\JWT\Validation\SignedWith: # Interface
        class: Lcobucci\JWT\Validation\Constraint\SignedWith
        arguments: [ '@Lcobucci\JWT\Signer', '@jwt_auth.private_key' ]

    Lcobucci\JWT\Validation\ValidAt: # Interface
        class: Lcobucci\JWT\Validation\Constraint\StrictValidAt
        arguments: [ '@Psr\Clock\ClockInterface' ]
# < --- lcobucci/jwt ---

# > --- atlance/jwt-core  ---
    Atlance\JwtCore\Token\Validation\Constraint\HasClaim: # Class
        arguments: [ '%atlance_jwt_auth.client_claim_name%' ]

    Atlance\JwtCore\Token\Contracts\Builder\Decorator\NullableArgsDecoratorInterface: # Interface
        class: Atlance\JwtCore\Token\Builder
        arguments:
            - '@Lcobucci\JWT\Builder'
            - '@Lcobucci\JWT\Signer'
            - '@jwt_auth.private_key'
            - '@Psr\Clock\ClockInterface'
            - '%atlance_jwt_auth.ttl%'

    Atlance\JwtCore\Token\Contracts\Factory\TokenFactoryInterface: # Interface
        class: Atlance\JwtCore\Token\Factory\TokenFactory
        arguments: [ '@Atlance\JwtCore\Token\Contracts\Builder\Decorator\NullableArgsDecoratorInterface' ]

    Atlance\JwtCore\Token\Validation\Validator: # Class
        arguments:
            - '@Lcobucci\JWT\Validator'
            - '@Lcobucci\JWT\Validation\SignedWith'
            - '@Lcobucci\JWT\Validation\ValidAt'
            - '@Atlance\JwtCore\Token\Validation\Constraint\HasClaim'

    Atlance\JwtCore\Token\Contracts\EncodeInterface: # Interface
        class: Atlance\JwtCore\Token\UseCase\Encode\Handler
        arguments:
            - '@Atlance\JwtCore\Token\Contracts\Factory\TokenFactoryInterface'
            - '@Atlance\JwtCore\Token\Validation\Validator'

    Atlance\JwtCore\Token\Contracts\DecodeInterface: # Interface
        class: Atlance\JwtCore\Token\UseCase\Decode\Handler
        arguments:
            - '@Lcobucci\JWT\Parser'
            - '@Atlance\JwtCore\Token\Validation\Validator'
# < --- atlance/jwt-core  ---

# > --- atlance/jwt-auth  ---
    Atlance\JwtAuth\Security\Factory\Contracts\UserDataSetFactoryInterface: # Interface
        class: Atlance\JwtAuth\Security\Factory\UserDataSetFactory
        arguments:
            $identifierClaimName: '%atlance_jwt_auth.client_claim_name%'

    Atlance\JwtAuth\Security\UseCase\Access\Token\HandlerInterface: # Interface
        class: Atlance\JwtAuth\Security\UseCase\Access\Token\Handler
        public: true
        arguments:
            $identifierClaimName: '%atlance_jwt_auth.client_claim_name%'

    Atlance\JwtAuth\Security\UseCase\Create\Token\HandlerInterface: # Interface
        class: Atlance\JwtAuth\Security\UseCase\Create\Token\Handler
        public: true

    Atlance\JwtAuth\Security\Factory\UserBadgeFactory:
        public: true
